"""Invariants that live in the documentation rather than in the code.

## Why this file exists

`SECURITY.md` tells an external security researcher, as the first thing it
asks of them, to read `docs/17-flagged-for-review.md` — the register of
what is already known-wrong — so that they do not spend their time
reporting something the project has already recorded. `ARCHITECTURE.md`
cites the same file eight times as the PROVENANCE for its review claims:
"reviewed (docs/17 F15 — ten service defects)".

The file was removed from the working tree while packaging a release, and
nothing noticed. Every one of those seventeen references became a link to
nothing, in the two documents whose entire job is to be trusted by somebody
outside this codebase — and the whole suite stayed green, because no test
has ever read a document.

A citation to a file that does not exist is worse than no citation: it
reads as evidence, and it is checkable only by the reader, who is the one
person who cannot check it.

Pure — no database. These read the shipped documents.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]

#: `[text](target.md)` and `[text](target.md#anchor)`. Bare URLs and
#: fenced code are not links and are not checked.
_MD_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+\.md)(?:#[^)\s]*)?\)")

#: The packaged export is a `git archive` copy of the tree, regenerated by
#: `package_release.ps1`. Checking it would report every finding twice.
#: `.claude` is the agent harness's directory and holds whole worktree
#: copies of the repository while a pass is in flight (added 2026-09-09):
#: without skipping it, a run from the main checkout reads every document
#: in every worktree and reports each finding once per copy, against text
#: this checkout does not contain. `check_source_hygiene.py` skips it for
#: the same reason.
_SKIP_PARTS = {".venv", ".git", "node_modules", ".claude"}
_SKIP_DIRS = ("NocTORnal - Alpha Release",)


def _docs() -> list[Path]:
    out = []
    for md in ROOT.rglob("*.md"):
        # Match on the path RELATIVE to the repository, not the absolute one.
        # The harness checks this tree out under `<main>/.claude/worktrees/`,
        # so an absolute match on `.claude` skipped every document in a
        # worktree and this returned an empty list -- and every check below
        # passed by doing nothing, which `test_there_are_documents_to_check`
        # exists to catch (and did, 2026-09-09).
        rel = md.relative_to(ROOT)
        if _SKIP_PARTS & set(rel.parts):
            continue
        if any(d in str(rel) for d in _SKIP_DIRS):
            continue
        out.append(md)
    return sorted(out)


def test_there_are_documents_to_check():
    """A glob that silently matches nothing turns every check below into a
    check that passes by doing nothing — the failure mode this file was
    written about, reappearing in the file itself."""
    docs = _docs()
    assert len(docs) > 20, f"only found {len(docs)} markdown files under {ROOT}"


@pytest.mark.parametrize("doc", _docs(), ids=lambda p: p.name)
def test_every_document_link_resolves(doc: Path):
    """A link to a file that is not in the tree."""
    broken = []
    for target in _MD_LINK.findall(doc.read_text(encoding="utf-8")):
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        if not (doc.parent / target).resolve().exists():
            broken.append(target)
    assert not broken, (
        f"{doc.relative_to(ROOT).as_posix()} links to files that do not "
        f"exist: {broken}")


#: The two documents written for somebody OUTSIDE this codebase. A dangling
#: reference costs more here than anywhere else in the tree, because the
#: reader has no way to tell a missing file from a file they cannot see.
_OUTWARD_FACING = ("SECURITY.md", "README.md", "ARCHITECTURE.md")


@pytest.mark.parametrize("name", _OUTWARD_FACING)
def test_the_outward_facing_documents_cite_files_that_exist(name: str):
    """Belt to the braces above: these three are checked by name so that
    deleting one does not quietly reduce the coverage of this file to the
    documents that happen to remain."""
    doc = ROOT / name
    assert doc.exists(), f"{name} is missing from the repository root"
    missing = [
        target for target in _MD_LINK.findall(doc.read_text(encoding="utf-8"))
        if not target.startswith(("http://", "https://", "mailto:"))
        and not (doc.parent / target).resolve().exists()
    ]
    assert not missing, f"{name} cites missing documents: {missing}"


def test_the_known_wrong_register_is_present():
    """`docs/17` is named by SECURITY.md as the first thing a researcher
    should read and by ARCHITECTURE.md as the evidence that each phase was
    reviewed. It is the one document whose absence makes other documents
    lie, so it is asserted on its own rather than only as a link target."""
    register = ROOT / "docs" / "17-flagged-for-review.md"
    assert register.exists(), (
        "docs/17-flagged-for-review.md is missing, and SECURITY.md sends "
        "external researchers to it")
    text = register.read_text(encoding="utf-8")
    assert "CHANGE LIKELY" in text and "ACCEPTED COST" in text, (
        "the register no longer carries its severity vocabulary, so the "
        "citations to it (docs/17 F15, F19, F20) resolve to something else")

# ---------------------------------------------------------------------------
# A citation to code, not to a document
# ---------------------------------------------------------------------------
#
# Everything above proves that a cited DOCUMENT exists. The documents that
# matter most here are not written in documents -- `ROADMAP-REMAINING.md` is
# written almost entirely in three other currencies: source files
# (`retention.py`), test names (`test_a_locked_exhibit_stays_due...`) and
# endpoints (`GET /audit/custody/verify`). Each is a claim about the tree,
# each reads as evidence, and until 2026-09-02 nothing checked any of them.
#
# These are deliberately forgiving. A prose mention of a name is not a
# citation, and a document is allowed to describe something that was
# REMOVED as long as it says so; the checks below therefore look only at
# names written in the shape this project uses for a live reference, and
# report the whole set at once rather than failing on the first.

_SRC = ROOT / "apps" / "api" / "src" / "noctornal_api"
_TESTS = ROOT / "apps" / "api" / "tests"

#: `` `something_py.py` `` in backticks -- the shape this tree uses when it
#: means "this module", as opposed to a bare word in a sentence.
_PY_CITE = re.compile(r"`([a-z0-9_]+\.py)`")

#: `` `test_whatever` `` or `` `test_whatever()` ``.
_TEST_CITE = re.compile(r"`(test_[a-z0-9_]+)\(?\)?`")

#: `GET /path`, `POST /path` -- the shape the docs use for a route.
_ROUTE_CITE = re.compile(r"`(GET|POST|PATCH|PUT|DELETE) (/[A-Za-z0-9_{}/-]+)`")

#: Modules named in the docs that are deliberately not in `noctornal_api`,
#: or are named as examples rather than as citations.
_PY_EXEMPT = {
    "setup.py", "conftest.py", "__init__.py", "manage.py", "env.py",
    "package_release.py", "app.py", "main.py",
}


def _roadmap_and_architecture() -> list[Path]:
    return [p for p in (ROOT / "ROADMAP-REMAINING.md",
                        ROOT / "ARCHITECTURE.md") if p.exists()]


def test_cited_python_modules_exist():
    """A roadmap that names a module which is gone is worse than silent.

    It is read as a map of the tree by somebody deciding what to work on
    next, and a name that resolves to nothing costs them the time it takes
    to discover that -- which is exactly the time the roadmap exists to
    save.
    """
    known = {p.name for p in _SRC.rglob("*.py")}
    known |= {p.name for p in _TESTS.rglob("*.py")}
    known |= {p.name for p in (ROOT / "scripts").rglob("*.py")}
    known |= {p.name for p in (ROOT / "db").rglob("*.py")}
    # `packages/ontology` is a separate distribution but the same tree, and
    # ARCHITECTURE.md cites `generate.py` and `normalisers.py` from it.
    known |= {p.name for p in (ROOT / "packages").rglob("*.py")}
    assert len(known) > 50, f"only found {len(known)} modules -- tree moved?"

    missing: dict[str, set[str]] = {}
    for doc in _roadmap_and_architecture():
        gone = {
            name for name in _PY_CITE.findall(doc.read_text(encoding="utf-8"))
            if name not in known and name not in _PY_EXEMPT
        }
        if gone:
            missing[doc.name] = gone
    assert not missing, (
        f"documents cite Python modules that are not in the tree: {missing}. "
        f"Either the module moved and the citation is stale, or it was "
        f"deleted and the paragraph around it is now describing nothing.")


def test_cited_test_names_exist():
    """The roadmap's evidence is very often a test name.

    "asserted by `test_the_console_is_served_under_the_ui_csp`" is the
    strongest kind of claim this file makes, because a reader can run it.
    A renamed test turns that into a claim that cannot be checked, which
    is the failure mode this whole file exists to prevent.
    """
    defined: set[str] = set()
    for path in _TESTS.rglob("test_*.py"):
        defined |= set(re.findall(r"^def (test_[a-z0-9_]+)",
                                  path.read_text(encoding="utf-8"),
                                  re.M))
    assert len(defined) > 500, f"only found {len(defined)} tests -- tree moved?"

    missing: dict[str, set[str]] = {}
    for doc in _roadmap_and_architecture():
        text = doc.read_text(encoding="utf-8")
        gone = {n for n in _TEST_CITE.findall(text) if n not in defined}
        # `test_error_invariants` is a FILE, cited without its extension --
        # a legitimate way to name a suite, and not a missing function. Only
        # a name that is neither a defined test nor a test module is stale.
        gone = {n for n in gone
                if not (_TESTS / f"{n}.py").exists()}
        if gone:
            missing[doc.name] = gone
    assert not missing, (
        f"documents cite tests that no longer exist: {missing}. A test name "
        f"in these documents is an invitation to go and run it.")


def test_cited_endpoints_are_routed():
    """`GET /audit/custody/verify` has to be a route, not a plan.

    Three of the endpoints this project documented were, at various points,
    written down before they were routed or after they were renamed. The
    app's own router table is the only honest source for what exists.
    """
    from noctornal_api.http.app import create_app

    # NOT `app.routes`: this app mounts its routers as `_IncludedRouter`
    # objects, which carry neither `.path` nor a walkable `.routes`, so
    # iterating the attribute returns three paths and a test built on it
    # would pass by checking almost nothing. The generated schema is the
    # only enumeration that agrees with what the server actually serves.
    app = create_app()
    routed: set[str] = set(app.openapi().get("paths", {}))
    # `/healthz` is routed with include_in_schema=False, so the schema alone
    # would report the liveness probe as undocumented-and-missing. Union the
    # routes attached directly to the app, which is where those live.
    routed |= {r.path for r in app.routes if getattr(r, "path", None)}
    assert len(routed) > 80, f"only saw {len(routed)} routes -- app changed?"

    #: The docs write `/cases/{id}/...` where the app declares
    #: `/cases/{case_id}/...`, and both are prefixed `/api/v1`. Compare on
    #: a shape that ignores both differences.
    def norm(p: str) -> str:
        p = re.sub(r"^/api/v1", "", p)
        return re.sub(r"\{[a-z_]+\}", "{}", p)

    have = {norm(p) for p in routed}

    #: Matched on the TAIL, not on equality. ARCHITECTURE.md documents each
    #: router's routes relative to that router's own prefix -- `POST /nodes`
    #: under the graph router, `GET /me` under auth -- while the roadmap
    #: writes some of them absolute. Requiring equality would fail on 58
    #: routes that all exist, which is a test that reports the wrong thing
    #: about itself. The tail match still catches the case worth catching:
    #: a path that appears nowhere in the routing table at all.
    def routed_somewhere(path: str) -> bool:
        want = norm(path)
        return any(p == want or p.endswith(want) for p in have)

    missing: dict[str, set[str]] = {}
    for doc in _roadmap_and_architecture():
        text = doc.read_text(encoding="utf-8")
        gone = {
            f"{verb} {path}"
            for verb, path in _ROUTE_CITE.findall(text)
            if not routed_somewhere(path)
        }
        if gone:
            missing[doc.name] = gone
    assert not missing, (
        f"documents cite endpoints the app does not route: {missing}. An "
        f"endpoint written down before it is routed reads exactly like one "
        f"that shipped.")


# ---------------------------------------------------------------------------
# The stack the documents describe must be the stack in the tree
# ---------------------------------------------------------------------------
#
# The 2026-07 design sketch (docs/02 as first written) described Next.js,
# sigma.js over WebGL, OpenFGA or SpiceDB, NATS, Arq or Celery workers,
# three network trust zones and UUIDv7 ids. None of that was built. What
# shipped is one FastAPI process on Postgres 16 + pgvector, Redis, MinIO and
# Mailpit, a vanilla HTML/CSS/JS console under a strict CSP, a five-part
# access gate answered from Postgres, a Canvas 2D sociogram with a
# Barnes-Hut layout worker, and uuid4()/gen_random_uuid() ids. OpenFGA and
# NATS were removed from the compose file on 2026-07-26 (R13).
#
# On 2026-09-09 an external review of Alpha 4 found the removed stack still
# described as current in 33 places across CONVENTIONS.md, QUICKSTART.md,
# ARCHITECTURE.md and docs/00, 02, 05, 09 and 14 -- every one of them
# accurate about the sketch and wrong about the program. A live document
# that names a component the tree does not contain is this codebase's
# signature defect in prose form.
#
# The rule below is deliberately narrow. History is allowed: a decision
# record may say "OpenFGA was the plan and was superseded", and a roadmap
# may say "sigma.js is not in the tree". What is not allowed is the name
# on a line that does not ALSO say, on that same line, that the thing is
# gone -- because a reader takes an unmarked mention as a description.

#: The removed technologies, as they are actually spelled in these files.
_REMOVED_STACK = re.compile(
    r"(?i)next\.?js|sigma\.?js|webgl|openfga|spicedb|\bnats\b|celery|\barq\b|uuid ?v7")

#: THE MARKER. A line naming a removed technology must also carry one of
#: these words, case-insensitively: `superseded`, `removed`, `replaced`, or
#: the phrase `not in the tree`. The first two are the vocabulary the
#: decision records and the compose file already use for the same purpose;
#: the last two are what ROADMAP-REMAINING.md and docs/09 already said about
#: sigma.js before this rule existed, and a rule that would fail the two
#: documents that were already honest would be the wrong rule. When you
#: write a new historical mention, put one of these four on its line.
_HISTORY_MARKER = re.compile(r"(?i)superseded|removed|replaced|not in the tree")

#: Until 2026-09-09 the root README was excluded here as "the owner's
#: document", and carried sigma.js / WebGL, 1269 tests and 52 revisions
#: through five alphas while every other document was held to the tree.
#: An exclusion for the file a new reader opens first is the defect this
#: file exists to catch, wearing a shield. Nothing is excluded now.


def test_no_document_describes_the_removed_stack():
    """Every mention of the 2026-07 sketch's stack is marked as history.

    Fails on the tree as it stood on 2026-09-09 (33 unmarked mentions) and
    reports every offending line at once, so the fix is one pass rather
    than thirty-three."""
    offenders: list[str] = []
    for doc in _docs():
        rel = doc.relative_to(ROOT).as_posix()
        for lineno, line in enumerate(doc.read_text(encoding="utf-8").splitlines(), 1):
            if _REMOVED_STACK.search(line) and not _HISTORY_MARKER.search(line):
                offenders.append(f"{rel}:{lineno}: {line.strip()[:110]}")
    assert not offenders, (
        "documents describe a stack that is not in the tree, on lines that do "
        "not say so (a line may name it only alongside 'superseded', 'removed', "
        "'replaced' or 'not in the tree'):\n  " + "\n  ".join(offenders))


# ---------------------------------------------------------------------------
# The counters must be the counters
# ---------------------------------------------------------------------------
#
# "1206 passing", "1269 tests", "Alembic head 0052" -- every one a snapshot
# that was true on the day it was written and copied forward by hand until
# it was not. The external review of 2026-09-09 found three different test
# totals and two different migration counts across the tree, none of them
# current. A number a reader can check is a claim; these hold the two
# outward-facing documents' claims to what the tree contains.
#
# The root README joined the list on 2026-09-09 (see the stack rule above),
# and CONVENTIONS.md with it: the working agreement quoted a revision count
# one short of the chain the same day.

_COUNTED_DOCS = ("release/README.md", "ARCHITECTURE.md", "README.md",
                 "CONVENTIONS.md")

#: A four-digit number immediately followed by `tests` or `passing`
#: (`1206 passing`, `**1252 tests passing**`), or by `%20` and the same
#: word inside a badge URL (`tests-1269%20passing`: the README's shield
#: said 1269 on a 1627-function tree). Three-digit figures are left
#: alone: the documents quote historical per-phase counts ("it had 673
#: passing tests") as narrative, not as the suite's size.
_TEST_COUNT_CLAIM = re.compile(r"\b(\d{4})(?:\s+|%20)(?:tests|passing)\b")

#: `Alembic head 0052` / `Alembic head **0052**`.
_HEAD_CLAIM = re.compile(r"Alembic head\s+\*{0,2}(\d{4})\*{0,2}")

#: `59 revisions`, `52 Alembic migrations`, `59 Alembic revisions`: a count
#: of the migration chain, held to the number of version files.
_REVISION_COUNT_CLAIM = re.compile(
    r"\b(\d{2,3})\s+(?:Alembic\s+)?(?:revisions|migrations)\b")

#: One `def test_...`, sync or async, at any indentation -- so a test
#: method inside a class counts, as pytest counts it. This is the
#: definition the documents' figure is held to; state it beside the
#: figure when you write one.
_TEST_DEF = re.compile(r"^\s*(?:async )?def test_\w+", re.M)

_TEST_ROOTS = (_TESTS, ROOT / "packages" / "ontology" / "tests")


def _test_function_count() -> int:
    n = 0
    for root in _TEST_ROOTS:
        for path in root.rglob("test_*.py"):
            n += len(_TEST_DEF.findall(path.read_text(encoding="utf-8")))
    assert n > 500, f"only counted {n} test functions -- tree moved?"
    return n


def _alembic_head() -> str:
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "db" / "migrations"))
    cfg.set_main_option("path_separator", "os")   # silences a 1.16 deprecation
    return ScriptDirectory.from_config(cfg).get_current_head()


def _refresher():
    """`scripts/refresh_counters.py`, imported by path.

    The script is the single definition of what a live counter looks like
    and what its value is; this file only asserts that running it would
    change nothing. Two copies of the rule would drift, which is the
    defect under discussion.
    """
    import importlib.util

    path = ROOT / "scripts" / "refresh_counters.py"
    assert path.exists(), "scripts/refresh_counters.py is missing"
    spec = importlib.util.spec_from_file_location("refresh_counters", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_every_quoted_counter_is_the_tree_exactly():
    """No tolerance, because a tolerance is where the defect lives.

    This check allowed five per cent on the test total until 2026-09-10 --
    eighty tests at this size -- on the reasoning that a hand-maintained
    number cannot track a tree that gains tests every commit. The release
    that introduced the check then shipped a README claiming 1627 against
    a tree of 1639: stale, and green, because the drift fitted inside the
    band. The numbers are generated now, so the band is unnecessary and
    gone. `scripts/refresh_counters.py` defines which shapes are live
    claims, which regions of a document are history, and what each value
    is; this asserts only that running it would change nothing.
    """
    refresher = _refresher()
    values = refresher._values()
    stale: list[str] = []
    seen_total = 0
    for name, marker in refresher.CHECKED.items():
        doc = ROOT / name
        assert doc.exists(), f"{name} is missing"
        text = doc.read_text(encoding="utf-8").replace("\r\n", "\n")
        cut = refresher._live_region(text, marker)
        rewritten, seen = refresher._rewrite(text[:cut], values)
        seen_total += seen
        if rewritten != text[:cut]:
            for before, after in zip(text[:cut].splitlines(),
                                     rewritten.splitlines(), strict=False):
                if before != after:
                    stale.append(f"{name}: {before.strip()[:90]}")
    assert seen_total >= 10, (
        f"only {seen_total} counter claims matched -- the shapes moved and "
        f"this test is checking nothing")
    quoted = ", ".join(f"{k}={v}" for k, v in sorted(values.items()))
    assert not stale, (
        f"documents quote counters the tree does not have ({quoted}):\n  "
        + "\n  ".join(stale)
        + "\nRun `python scripts/refresh_counters.py` -- these are generated.")


def test_quoted_alembic_heads_are_the_chain_head():
    """`Alembic head NNNN` is checkable in one command, and both documents
    quoted a head six revisions stale on 2026-09-09."""
    head = _alembic_head()
    stale: list[str] = []
    for name in _COUNTED_DOCS:
        for m in _HEAD_CLAIM.finditer((ROOT / name).read_text(encoding="utf-8")):
            if m.group(1) != head:
                stale.append(f"{name}: '{m.group(0)}'")
    assert not stale, f"documents quote an Alembic head other than {head}: {stale}"


def _revision_file_count() -> int:
    n = len(list((ROOT / "db" / "migrations" / "versions").glob("0*.py")))
    assert n > 50, f"only {n} version files -- tree moved?"
    return n


def test_quoted_revision_counts_are_the_length_of_the_chain():
    """`52 revisions` in three places of the README on a 59-file chain,
    and `58 Alembic revisions (0001-0059)` in CONVENTIONS, on 2026-09-09.
    A count is checkable in one `ls`; hold it to that."""
    actual = _revision_file_count()
    stale: list[str] = []
    for name in _COUNTED_DOCS:
        text = (ROOT / name).read_text(encoding="utf-8")
        for m in _REVISION_COUNT_CLAIM.finditer(text):
            if int(m.group(1)) != actual:
                stale.append(f"{name}: '{m.group(0)}'")
    assert not stale, (
        f"documents quote a migration count other than the {actual} version "
        f"files in db/migrations/versions: {stale}")


# ---------------------------------------------------------------------------
# One completion figure
# ---------------------------------------------------------------------------

def test_every_quoted_completion_figure_is_the_one_the_roadmap_computes():
    """Three documents quoted three different overall figures on 2026-09-09:
    92.8% in the roadmap, ~92% in ARCHITECTURE, ~95% in release/README, and
    a stray 92.7 inside the roadmap's own explanation of the 92.8.

    Only `ROADMAP-REMAINING.md` WORKS the number out, as the unweighted mean
    of its ten per-phase rows. Everywhere else quotes it, and quoting is what
    drifted, so the quotations are generated from it.
    """
    refresher = _refresher()
    authority = refresher.completion_figure()
    wrong: list[str] = []
    for name, marker in refresher.CHECKED.items():
        text = (ROOT / name).read_text(encoding="utf-8").replace("\r\n", "\n")
        cut = refresher._live_region(text, marker)
        for line in text[:cut].splitlines():
            if not refresher._COMPLETION_LINE.search(line):
                continue
            found = refresher._PERCENT.search(line)
            if found and found.group(1) != authority:
                wrong.append(f"{name}: {line.strip()[:90]}")
    assert not wrong, (
        f"documents quote an overall completion other than {authority}% (the "
        f"mean ROADMAP-REMAINING.md computes):\n  " + "\n  ".join(wrong))


# ---------------------------------------------------------------------------
# The twelve invariants say the same twelve things in all three documents
# ---------------------------------------------------------------------------
#
# On 2026-09-09 CONVENTIONS and ARCHITECTURE were reworded so that invariant 7
# says credentials never leave the VAULT, and that the vault runs inside the
# API process because there is no collector. The README -- the invariant table
# a new reader actually meets -- kept saying "never leave the collector ...
# decrypted only in the worker process", naming two processes this build does
# not have. The release that put the README under this linter did not catch
# it, because the linter was looking for sigma.js.
#
# So this is not another list of forbidden words. Each invariant carries the
# one word that distinguishes it, and all three documents must use that word.
# A row reworded into something else fails whatever it was reworded to, which
# is the property a register of examples cannot have.

#: invariant number -> the word its statement must contain, in every document
#: that states it. Add a row here when an invariant is added.
_INVARIANT_KEYWORD = {
    1: "fact", 2: "person", 3: "propose", 4: "inferred",
    5: "overwritten", 6: "append-only", 7: "vault", 8: "egress",
    9: "durable", 10: "render", 11: "write-only", 12: "dropped",
}


def _table_rows(text: str) -> dict[int, str]:
    """`| 7 | ... | ... |` rows of a markdown table, by number."""
    out: dict[int, str] = {}
    for line in text.splitlines():
        m = re.match(r"\|\s*(\d{1,2})\s*\|(.*)$", line)
        if not m:
            continue
        number = int(m.group(1))
        if number in _INVARIANT_KEYWORD and number not in out:
            out[number] = m.group(2)
    return out


def _numbered_items(text: str) -> dict[int, str]:
    """`7. **Credentials never leave the vault.** ...` items, by number, each
    running to the next numbered item."""
    out: dict[int, str] = {}
    starts = [(int(m.group(1)), m.start())
              for m in re.finditer(r"(?m)^(\d{1,2})\.\s+\*\*", text)
              if int(m.group(1)) in _INVARIANT_KEYWORD]
    for i, (number, start) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
        out.setdefault(number, text[start:end])
    return out


def test_the_three_invariant_statements_agree():
    """README's table, CONVENTIONS' numbered list and ARCHITECTURE's table
    state the same twelve invariants, so each must use the word that
    distinguishes its own. A statement reworded into something the tree does
    not do fails here rather than in a reader's review."""
    sources = {
        "README.md": _table_rows(
            (ROOT / "README.md").read_text(encoding="utf-8")),
        "ARCHITECTURE.md": _table_rows(
            (ROOT / "ARCHITECTURE.md").read_text(encoding="utf-8")),
        "CONVENTIONS.md": _numbered_items(
            (ROOT / "CONVENTIONS.md").read_text(encoding="utf-8")),
    }
    missing: list[str] = []
    for name, rows in sources.items():
        absent = sorted(set(_INVARIANT_KEYWORD) - set(rows))
        assert not absent, f"{name} states no invariant {absent}"
        for number, keyword in _INVARIANT_KEYWORD.items():
            if keyword.lower() not in rows[number].lower():
                missing.append(
                    f"{name} invariant {number} does not say '{keyword}': "
                    f"{rows[number].strip()[:90]}")
    assert not missing, (
        "the invariant statements have drifted apart:\n  " + "\n  ".join(missing)
        + "\nAll three documents state the same twelve invariants; a rewording "
        "that drops the distinguishing word is how invariant 7 came to name a "
        "collector process this build does not have.")


# ---------------------------------------------------------------------------
# Things that are not true of the tree, in prose OR in source
# ---------------------------------------------------------------------------
#
# `_REMOVED_STACK` above covers the 2026-07 sketch's libraries. This covers
# the other half of the same class: behaviour that was DESIGNED and never
# built, which the tree went on describing in the present tense. The
# maintenance rule, stated so it is not guesswork: when a decision record
# says a thing was never built, add it here.

_NEVER_BUILT = re.compile(r"(?i)auto-?merge|cursor pagination")

#: A line may name one of them only if it also says, on that same line, that
#: it is not what the code does.
_NEVER_BUILT_MARKER = re.compile(
    r"(?i)superseded|removed|replaced|not in the tree|never built|"
    r"never implemented|"
    r"not\W{0,4}implemented|not automatic|merge lead|never auto-?merge|"
    r"must never|cannot auto-?merge|clustering only|as designed|"
    r"designed and never|it never was|never a")

#: Invariant 7 stated as though a separate process existed. A flat ban: the
#: honest phrasings name the VAULT and the API process.
_INVARIANT_7_MISSTATED = re.compile(
    r"(?i)credentials? never leaves? the collector"
    r"|decrypt\w* only in(?:side)? the (?:collector|worker)"
    r"|decryption happens only in the collector")

#: A decision record may QUOTE the superseded wording, which is how a
#: reader learns it was superseded -- decision 53 does exactly that.
_QUOTING_THE_OLD_WORDING = re.compile(
    r"(?i)reworded|superseded|corrected|invariant 7 said|until 2026|no separate collector|there is no collector")

#: Dated records: a changelog entry and a migration describe the day they
#: were written and are never rewritten.
_HISTORY_FILES = ("release/CHANGELOG.md", "db/migrations/")


def _prose_and_source() -> list[Path]:
    """Every live document, every source and test file, and the console.

    Not this file: it has to spell the forbidden phrases out to look for
    them, and a checker that fails on its own patterns is a checker
    somebody deletes."""
    out = [d for d in _docs()
           if not any(h in d.relative_to(ROOT).as_posix() for h in _HISTORY_FILES)]
    for root in (_SRC, _TESTS, ROOT / "packages" / "ontology" / "src",
                 ROOT / "packages" / "ontology" / "tests"):
        out.extend(p for p in root.rglob("*.py") if "__pycache__" not in p.parts)
    out.append(_SRC / "http" / "static" / "app.js")
    here = Path(__file__).resolve()
    return [p for p in out if p.resolve() != here]


def test_nothing_describes_a_behaviour_that_was_never_built():
    """Auto-merge is the case that survived the 2026-09-09 pass: CONVENTIONS
    was corrected, and the ontology definition, the Telegram normaliser, a
    comms test and the README went on saying `is_strong` feeds it. Cursor
    pagination is the same shape. Source and tests are read too, because
    that is where these four lived."""
    offenders: list[str] = []
    for path in _prose_and_source():
        rel = path.relative_to(ROOT).as_posix()
        for lineno, line in enumerate(
                path.read_text(encoding="utf-8").splitlines(), 1):
            if _NEVER_BUILT.search(line) and not _NEVER_BUILT_MARKER.search(line):
                offenders.append(f"{rel}:{lineno}: {line.strip()[:100]}")
    assert not offenders, (
        "these lines describe behaviour that was designed and never built, "
        "without saying so on the line (a strong-selector collision is a "
        "merge LEAD an analyst confirms; pagination is `limit`-capped):\n  "
        + "\n  ".join(offenders))


def test_invariant_7_is_never_stated_as_a_separate_process():
    """There is no collector process and no worker process. `PersonaVault`
    runs inside the API process, so invariant 7 bounds the shape of the code
    and not the blast radius of a compromised host -- which is what
    CONVENTIONS, ARCHITECTURE and docs/05 say, and what the README's
    invariant table did not say until 2026-09-10."""
    offenders: list[str] = []
    for path in _prose_and_source():
        rel = path.relative_to(ROOT).as_posix()
        for lineno, line in enumerate(
                path.read_text(encoding="utf-8").splitlines(), 1):
            if (_INVARIANT_7_MISSTATED.search(line)
                    and not _QUOTING_THE_OLD_WORDING.search(line)):
                offenders.append(f"{rel}:{lineno}: {line.strip()[:100]}")
    assert not offenders, (
        "invariant 7 is stated as though the credentials lived in a separate "
        "process; name the VAULT, and say it runs inside the API process:\n  "
        + "\n  ".join(offenders))
