"""`db/schema.sql` calls itself a mirror of the migrations. This holds it to that.

## What was wrong before 2026-09-09

docs/00 decision 17 (2026-07-24) made the Alembic chain authoritative and
kept `db/schema.sql` as a "mirrored reference", maintained by hand. Nothing
checked the mirror. By 2026-09-09 the migrations created TEN schemas and the
file named FIVE -- `comms`, `deception`, `ingest`, `lab` and `notify` were
absent, along with everything revisions 0040-0058 added -- while
ARCHITECTURE.md, CONVENTIONS.md and the migration `env.py` all still sent
readers to it as "the readable end-to-end DDL". docs/17 F17(b) had even
recorded the gap on 2026-07-25 and the file was not fixed.

The file is now GENERATED by `scripts/dump_schema.py`, and its header names
the revision it was dumped at. These tests read the migrations, the file and
(when there is one) the database, and refuse a mirror that disagrees with
any of them.

Two checks are pure and read only the tree; the third is gated on
`DATABASE_URL` like every `_pg` suite and reads the live database.
"""
from __future__ import annotations

import os
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
SCHEMA_SQL = ROOT / "db" / "schema.sql"
MIGRATIONS = ROOT / "db" / "migrations" / "versions"

#: `CREATE SCHEMA core;` / `CREATE SCHEMA IF NOT EXISTS core;` -- the two
#: forms the migrations use inside their SQL strings, and the one pg_dump
#: emits. Matched case-insensitively so a migration written either way counts.
_CREATE_SCHEMA = re.compile(
    r"CREATE SCHEMA(?: IF NOT EXISTS)?\s+\"?([a-z_][a-z0-9_]*)\"?", re.I)

#: Written by `scripts/dump_schema.py` into the header. The literal shape is
#: shared with that script; if it changes there, this must change too.
_REVISION_LINE = re.compile(r"^-- Alembic revision: (\w+)$", re.M)


def _schemas_created_by_migrations() -> set[str]:
    found: set[str] = set()
    for path in MIGRATIONS.glob("*.py"):
        found |= {m.lower() for m in
                  _CREATE_SCHEMA.findall(path.read_text(encoding="utf-8"))}
    return found


def _schemas_named_by_mirror() -> set[str]:
    return {m.lower() for m in
            _CREATE_SCHEMA.findall(SCHEMA_SQL.read_text(encoding="utf-8"))}


def _mirror_revision() -> str | None:
    m = _REVISION_LINE.search(SCHEMA_SQL.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def _alembic_head() -> str:
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    cfg = Config(str(ROOT / "alembic.ini"))
    # alembic.ini says `script_location = db/migrations`, relative to the
    # CWD it is invoked from. pytest runs from apps/api, so make it absolute.
    cfg.set_main_option("script_location", str(ROOT / "db" / "migrations"))
    # Alembic 1.16 warns when the ini has no path_separator; the ini is not
    # this test's to change, and the value is irrelevant to reading heads.
    cfg.set_main_option("path_separator", "os")
    return ScriptDirectory.from_config(cfg).get_current_head()


def test_the_migrations_create_several_schemas():
    """A regex that matches nothing turns the check below into one that
    passes by comparing an empty set -- the failure mode of this whole
    pass, reappearing in the test that guards against it."""
    created = _schemas_created_by_migrations()
    assert len(created) >= 5, f"only found {len(created)} schemas in {MIGRATIONS}"
    assert "core" in created and "audit" in created


def test_the_mirror_names_every_schema_the_migrations_create():
    """Five of ten, until 2026-09-09. A mirror that omits half the estate
    is worse than none, because the reader it was written for -- somebody
    outside the codebase -- has no way to see what is not there."""
    expected = _schemas_created_by_migrations()
    have = _schemas_named_by_mirror()
    missing = sorted(expected - have)
    assert not missing, (
        f"db/schema.sql does not create schemas the migrations create: "
        f"{missing}. Regenerate it: python scripts/dump_schema.py")


def test_the_mirror_header_names_the_chain_head():
    """The file must say which revision it mirrors, and it must be the head.

    `scripts/dump_schema.py` writes the revision the DATABASE was at, not
    `alembic heads`, precisely so that a dump taken from a database that is
    behind will say so here and be refused."""
    rev = _mirror_revision()
    assert rev is not None, (
        "db/schema.sql carries no '-- Alembic revision: NNNN' header line, so "
        "nobody can tell which revision it mirrors. Regenerate it with "
        "scripts/dump_schema.py")
    head = _alembic_head()
    assert rev == head, (
        f"db/schema.sql mirrors revision {rev} but the chain's head is {head}. "
        f"Regenerate it against a database at head.")


@pytest.mark.skipif(
    not os.environ.get("DATABASE_URL"),
    reason="DATABASE_URL not set; the live-database leg of the mirror check is gated",
)
def test_the_live_database_agrees_with_the_mirror_and_the_migrations():
    """The third side. The two checks above compare the file to the tree;
    this compares both to what a database upgraded to head actually holds,
    which is what the CI step `Schema mirror matches the migrations`
    diffs in full. Here: same revision, and every schema the migrations
    create exists."""
    import psycopg

    url = re.sub(r"^postgresql\+psycopg(?:2)?://", "postgresql://",
                 os.environ["DATABASE_URL"])
    with psycopg.connect(url) as conn:
        live = [r[0] for r in
                conn.execute("SELECT version_num FROM public.alembic_version")]
        namespaces = {r[0] for r in conn.execute("SELECT nspname FROM pg_namespace")}

    assert live == [_mirror_revision()], (
        f"the database is at {live} but db/schema.sql says it mirrors "
        f"{_mirror_revision()}")
    missing = sorted(_schemas_created_by_migrations() - namespaces)
    assert not missing, f"schemas the migrations create are not in the database: {missing}"
