"""Generate the TypeScript types and the SQL seed from the definition.

Usage (from the repo root or the package dir):
    python -m noctornal_ontology.generate           # (re)write generated/
    python -m noctornal_ontology.generate --check   # exit 1 on drift

Outputs land in packages/ontology/generated/. Both files carry a
DO-NOT-EDIT header; the definition module is the only editable source.
The SQL output matches the shape of Alembic revision 0017 — a definition
change ships as a NEW data migration, never by editing 0017.
"""
from __future__ import annotations

import re as _re
import sys
from pathlib import Path

from noctornal_ontology.definition import EDGE_TYPES, NODE_TYPES, SELECTOR_TYPES

GENERATED_DIR = Path(__file__).resolve().parents[2] / "generated"

_HEADER_TS = (
    "// GENERATED by noctornal_ontology.generate — DO NOT EDIT.\n"
    "// Source of truth: packages/ontology/src/noctornal_ontology/definition.py\n"
)
_HEADER_SQL = (
    "-- GENERATED by noctornal_ontology.generate — DO NOT EDIT.\n"
    "-- Source of truth: packages/ontology/src/noctornal_ontology/definition.py\n"
    "-- Covers the three ontology tables only (roles/permissions are IAM,\n"
    "-- seeded by Alembic revision 0017). Idempotent by primary key.\n"
    "-- NOTE: ON CONFLICT DO NOTHING means re-applying this over a CHANGED\n"
    "-- definition silently keeps the old rows — vocabulary changes ship as\n"
    "-- new Alembic revisions; drift is caught by tests/test_db_parity.py.\n"
)


# Keys travel unquoted inside Postgres text[] literals; anything outside
# this alphabet would corrupt the generated seed, so fail generation loud.
_SAFE_KEY = _re.compile(r"^[A-Z][A-Z0-9_]*$")


def _ts_str(s: str) -> str:
    return "'" + (
        s.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace(" ", "\\u2028")
        .replace(" ", "\\u2029")
    ) + "'"


def _sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _sql_bool(b: bool) -> str:
    return "true" if b else "false"


def _sql_text_array(items: tuple[str, ...]) -> str:
    return "'{" + ",".join(items) + "}'"


def render_typescript() -> str:
    out: list[str] = [_HEADER_TS]

    node_keys = " | ".join(_ts_str(n.key) for n in NODE_TYPES)
    out.append(f"export type NodeTypeKey = {node_keys};\n")
    edge_keys = " | ".join(_ts_str(e.key) for e in EDGE_TYPES)
    out.append(f"export type EdgeTypeKey = {edge_keys};\n")
    selector_keys = " | ".join(_ts_str(s.key) for s in SELECTOR_TYPES)
    out.append(f"export type SelectorTypeKey = {selector_keys};\n")
    out.append("export type NodeCategory = 'ACTOR' | 'ARTEFACT' | 'CONTEXT';\n")

    out.append("""export interface NodeTypeDef {
  key: NodeTypeKey;
  displayName: string;
  category: NodeCategory;
  colourToken: string;
  sortOrder: number;
}

export interface EdgeTypeDef {
  key: EdgeTypeKey;
  displayName: string;
  inverseName: string;
  isDirected: boolean;
  /** +1 trust/affiliation, -1 distrust/conflict, 0 neutral/structural. */
  defaultSign: -1 | 0 | 1;
  srcNodeTypes: readonly NodeTypeKey[];
  dstNodeTypes: readonly NodeTypeKey[];
  /** false = identity plumbing; excluded from SNA metrics by default. */
  isSocialTie: boolean;
}

export interface SelectorTypeDef {
  key: SelectorTypeKey;
  displayName: string;
  /** Strong enough to auto-merge identities on its own. */
  isStrong: boolean;
  isPii: boolean;
  /** Name of the normaliser (implemented in Python; mirror before use). */
  normaliser: string;
}
""")

    out.append("export const NODE_TYPES: readonly NodeTypeDef[] = [")
    for n in NODE_TYPES:
        out.append(
            f"  {{ key: {_ts_str(n.key)}, displayName: {_ts_str(n.display_name)}, "
            f"category: {_ts_str(n.category)}, colourToken: {_ts_str(n.colour_token)}, "
            f"sortOrder: {n.sort_order} }},"
        )
    out.append("] as const;\n")

    out.append("export const EDGE_TYPES: readonly EdgeTypeDef[] = [")
    for e in EDGE_TYPES:
        src = "[" + ", ".join(_ts_str(t) for t in e.src_node_types) + "]"
        dst = "[" + ", ".join(_ts_str(t) for t in e.dst_node_types) + "]"
        out.append(
            f"  {{ key: {_ts_str(e.key)}, displayName: {_ts_str(e.display_name)}, "
            f"inverseName: {_ts_str(e.inverse_name)}, isDirected: {str(e.is_directed).lower()}, "
            f"defaultSign: {e.default_sign}, srcNodeTypes: {src}, dstNodeTypes: {dst}, "
            f"isSocialTie: {str(e.is_social_tie).lower()} }},"
        )
    out.append("] as const;\n")

    out.append("export const SELECTOR_TYPES: readonly SelectorTypeDef[] = [")
    for s in SELECTOR_TYPES:
        out.append(
            f"  {{ key: {_ts_str(s.key)}, displayName: {_ts_str(s.display_name)}, "
            f"isStrong: {str(s.is_strong).lower()}, isPii: {str(s.is_pii).lower()}, "
            f"normaliser: {_ts_str(s.normaliser)} }},"
        )
    out.append("] as const;\n")

    return "\n".join(out)


def render_sql() -> str:
    for coll in (NODE_TYPES, EDGE_TYPES, SELECTOR_TYPES):
        for item in coll:
            if not _SAFE_KEY.match(item.key):
                raise ValueError(f"key {item.key!r} unsafe for SQL array literals")
    for e in EDGE_TYPES:
        for t in (*e.src_node_types, *e.dst_node_types):
            if not _SAFE_KEY.match(t):
                raise ValueError(f"endpoint {t!r} unsafe for SQL array literals")

    out: list[str] = [_HEADER_SQL, "SET search_path = core, public;\n"]

    out.append("INSERT INTO node_type (key, display_name, category, colour_token, sort_order) VALUES")
    rows = [
        f"({_sql_str(n.key)}, {_sql_str(n.display_name)}, {_sql_str(n.category)}, "
        f"{_sql_str(n.colour_token)}, {n.sort_order})"
        for n in NODE_TYPES
    ]
    out.append(",\n".join(rows))
    out.append("ON CONFLICT (key) DO NOTHING;\n")

    out.append(
        "INSERT INTO edge_type (key, display_name, inverse_name, is_directed, "
        "default_sign, src_node_types, dst_node_types, is_social_tie) VALUES"
    )
    rows = [
        f"({_sql_str(e.key)}, {_sql_str(e.display_name)}, {_sql_str(e.inverse_name)}, "
        f"{_sql_bool(e.is_directed)}, {e.default_sign}, "
        f"{_sql_text_array(e.src_node_types)}, {_sql_text_array(e.dst_node_types)}, "
        f"{_sql_bool(e.is_social_tie)})"
        for e in EDGE_TYPES
    ]
    out.append(",\n".join(rows))
    out.append("ON CONFLICT (key) DO NOTHING;\n")

    out.append("INSERT INTO selector_type (key, display_name, is_strong, is_pii, normaliser) VALUES")
    rows = [
        f"({_sql_str(s.key)}, {_sql_str(s.display_name)}, {_sql_bool(s.is_strong)}, "
        f"{_sql_bool(s.is_pii)}, {_sql_str(s.normaliser)})"
        for s in SELECTOR_TYPES
    ]
    out.append(",\n".join(rows))
    out.append("ON CONFLICT (key) DO NOTHING;\n")

    return "\n".join(out)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    targets = {
        GENERATED_DIR / "ontology.ts": render_typescript(),
        GENERATED_DIR / "seed_ontology.sql": render_sql(),
    }
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    drift = False
    for path, content in targets.items():
        if check:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                print(f"DRIFT: {path.name} does not match the definition", file=sys.stderr)
                drift = True
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path}")
    if check and not drift:
        print("generated files match the definition")
    return 1 if drift else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
